import { useTranslation } from "react-i18next";

export const lowercaseFirstLetter = (str) => {
    return str.charAt(0).toLowerCase() + str.slice(1);
};
export const dashboardStyles = () => {
    const { t } = useTranslation("formBuilder");
    return [
        {
            id: "card",
            leble: t("CARD"),
            icon: "material-solid:credit_card",
        },
        {
            id: "grid",
            leble: t("GRID"),
            icon: "material-solid:grid_on",
        },
        {
            id: "list",
            leble: t("LIST"),
            icon: "material-solid:view_list",
        },
        {
            id: "table",
            leble: t("TABLE"),
            icon: "material-solid:table_chart",
        },
    ];
};

export const navigationItems = [
    // {
    //     _id: "employees",
    //     id: "employees",
    //     label: "Employees",
    //     icon: "material-solid:account_circle",
    //     navContent: [
    //         {
    //             element_id: "109",
    //             element_type: "collection_ele",
    //             element_style: "table",
    //             element_icon: "material-solid:account_circle",
    //             collection_name: "Employees",
    //             element_data: [
    //                 {
    //                     _id: "1",
    //                     data: {
    //                         name: "sam",
    //                         email: "sam@gmail.com",
    //                         contact: "12345",
    //                     },
    //                     form: [],
    //                 },
    //                 {
    //                     _id: "2",
    //                     data: {
    //                         name: "sam2",
    //                         email: "sam2@gmail.com",
    //                         contact: "123452",
    //                     },
    //                     form: [],
    //                 },
    //                 {
    //                     _id: "3",
    //                     data: {
    //                         name: "sam3",
    //                         email: "sam3@gmail.com",
    //                         contact: "123453",
    //                     },
    //                     form: [],
    //                 },
    //             ],
    //         },
    //         {
    //             element_id: "19",
    //             element_type: "form_ele",
    //             element_data: [
    //                 {
    //                     id: new Date().valueOf(),
    //                     placeholder: "",
    //                     key: "first_name",
    //                     type: "TextField",
    //                     icon: "material-solid:text_format",
    //                     attributes: {
    //                         width: "match_parent",
    //                         height: "wrap_content",
    //                         label: null,
    //                         text: "",
    //                         hint: "Name",
    //                         textColor: "#FF0000",
    //                         maxLengthOfChar: null,
    //                         inputType: "text",
    //                         display_format: null,
    //                         saveRestoreLabel: null,
    //                         saveRestoreDisable: null,
    //                         saveRestoreVisible: null,
    //                         cancelClearLabel: null,
    //                         cancelClearDisable: null,
    //                         cancelClearVisible: null,
    //                         dropLabel: null,
    //                         dropDisable: null,
    //                         dropVisible: null,
    //                     },
    //                     validations: [
    //                         {
    //                             type: "Name",
    //                             condition: null,
    //                             message: "Please enter first name",
    //                         },
    //                     ],
    //                     options: null,
    //                     is_required: true,
    //                 },
    //                 {
    //                     id: 2,
    //                     key: "email",
    //                     placeholder: "",
    //                     type: "TextField",
    //                     icon: "material-solid:email",
    //                     attributes: {
    //                         width: "match_parent",
    //                         height: "wrap_content",
    //                         label: null,
    //                         text: "",
    //                         hint: "Email",
    //                         textColor: "#FF0000",
    //                         maxLengthOfChar: null,
    //                         inputType: "email",
    //                         display_format: null,
    //                         saveRestoreLabel: null,
    //                         saveRestoreDisable: null,
    //                         saveRestoreVisible: null,
    //                         cancelClearLabel: null,
    //                         cancelClearDisable: null,
    //                         cancelClearVisible: null,
    //                         dropLabel: null,
    //                         dropDisable: null,
    //                         dropVisible: null,
    //                     },
    //                     validations: [
    //                         {
    //                             type: "Email",
    //                             condition: null,
    //                             message: "Please enter your email",
    //                         },
    //                     ],
    //                     options: null,
    //                     is_required: true,
    //                 },
    //             ],
    //         },
    //     ],
    // },
    {
        _id: "formScreen",
        id: "formScreen",
        label: "Form Screen",
        icon: "heroicons-outline:star",
        navContent: [
            {
                element_id: "10987",
                element_type: "collection_ele",
                element_style: "table",
                element_icon: "material-solid:account_circle",
                collection_name: "Employees",
                element_data: [
                    {
                        _id: "1",
                        data: {
                            name: "sam",
                            email: "sam@gmail.com",
                            contact: "12345",
                        },
                        form: [
                            {
                                id: new Date().valueOf(),
                                key: "first_name",
                                type: "TextField",
                                attributes: {
                                    placeholder: "",
                                    width: "match_parent",
                                    height: "wrap_content",
                                    label: null,
                                    text: "sam",
                                    hint: "Name",
                                    textColor: "#FF0000",
                                    maxLengthOfChar: null,
                                    inputType: "text",
                                    display_format: null,
                                    saveRestoreLabel: null,
                                    saveRestoreDisable: null,
                                    saveRestoreVisible: null,
                                    cancelClearLabel: null,
                                    cancelClearDisable: null,
                                    cancelClearVisible: null,
                                    dropLabel: null,
                                    dropDisable: null,
                                    dropVisible: null,
                                },
                                validations: [
                                    {
                                        type: "Name",
                                        condition: null,
                                        message: "Please enter first name",
                                    },
                                ],
                                options: null,
                                is_required: true,
                            },
                            {
                                id: 2,

                                key: "email",
                                type: "TextField",
                                attributes: {
                                    placeholder: "",
                                    width: "match_parent",
                                    height: "wrap_content",
                                    label: null,
                                    text: "sam@gmail.com",
                                    hint: "Email",
                                    textColor: "#FF0000",
                                    maxLengthOfChar: null,
                                    inputType: "email",
                                    display_format: null,
                                    saveRestoreLabel: null,
                                    saveRestoreDisable: null,
                                    saveRestoreVisible: null,
                                    cancelClearLabel: null,
                                    cancelClearDisable: null,
                                    cancelClearVisible: null,
                                    dropLabel: null,
                                    dropDisable: null,
                                    dropVisible: null,
                                },
                                validations: [
                                    {
                                        type: "Email",
                                        condition: null,
                                        message: "Please enter your email",
                                    },
                                ],
                                options: null,
                                is_required: true,
                            },

                            {
                                id: 5,

                                key: "contact",
                                type: "TextField",
                                attributes: {
                                    placeholder: "",
                                    width: "match_parent",
                                    height: "wrap_content",
                                    label: null,
                                    text: "12345",
                                    hint: "Contact",
                                    textColor: "#FF0000",
                                    maxLengthOfChar: null,
                                    inputType: "number",
                                    display_format: null,
                                    saveRestoreLabel: null,
                                    saveRestoreDisable: null,
                                    saveRestoreVisible: null,
                                    cancelClearLabel: null,
                                    cancelClearDisable: null,
                                    cancelClearVisible: null,
                                    dropLabel: null,
                                    dropDisable: null,
                                    dropVisible: null,
                                },
                                validations: [
                                    {
                                        type: "Contact",
                                        condition: null,
                                        message: "Please enter your contact number",
                                    },
                                ],
                                options: null,
                                is_required: true,
                            },
                        ],
                    },
                    {
                        _id: "2",
                        data: {
                            name: "sam2",
                            email: "sam2@gmail.com",
                            contact: "123452",
                        },
                        form: [
                            {
                                id: new Date().valueOf(),
                                key: "first_name",
                                type: "TextField",
                                attributes: {
                                    width: "match_parent",
                                    height: "wrap_content",
                                    label: null,
                                    text: "",
                                    hint: "Name",
                                    textColor: "#FF0000",
                                    maxLengthOfChar: null,
                                    inputType: "text",
                                    display_format: null,
                                    saveRestoreLabel: null,
                                    saveRestoreDisable: null,
                                    saveRestoreVisible: null,
                                    cancelClearLabel: null,
                                    cancelClearDisable: null,
                                    cancelClearVisible: null,
                                    dropLabel: null,
                                    dropDisable: null,
                                    dropVisible: null,
                                },
                                validations: [
                                    {
                                        type: "Name",
                                        condition: null,
                                        message: "Please enter first name",
                                    },
                                ],
                                options: null,
                                is_required: true,
                            },
                            {
                                id: 2,
                                key: "email",
                                type: "TextField",
                                attributes: {
                                    width: "match_parent",
                                    height: "wrap_content",
                                    label: null,
                                    text: "",
                                    hint: "Email",
                                    textColor: "#FF0000",
                                    maxLengthOfChar: null,
                                    inputType: "email",
                                    display_format: null,
                                    saveRestoreLabel: null,
                                    saveRestoreDisable: null,
                                    saveRestoreVisible: null,
                                    cancelClearLabel: null,
                                    cancelClearDisable: null,
                                    cancelClearVisible: null,
                                    dropLabel: null,
                                    dropDisable: null,
                                    dropVisible: null,
                                },
                                validations: [
                                    {
                                        type: "Email",
                                        condition: null,
                                        message: "Please enter your email",
                                    },
                                ],
                                options: null,
                                is_required: true,
                            },

                            {
                                id: 5,
                                key: "contact",
                                type: "TextField",
                                attributes: {
                                    width: "match_parent",
                                    height: "wrap_content",
                                    label: null,
                                    text: "",
                                    hint: "Contact",
                                    textColor: "#FF0000",
                                    maxLengthOfChar: null,
                                    inputType: "number",
                                    display_format: null,
                                    saveRestoreLabel: null,
                                    saveRestoreDisable: null,
                                    saveRestoreVisible: null,
                                    cancelClearLabel: null,
                                    cancelClearDisable: null,
                                    cancelClearVisible: null,
                                    dropLabel: null,
                                    dropDisable: null,
                                    dropVisible: null,
                                },
                                validations: [
                                    {
                                        type: "Contact",
                                        condition: null,
                                        message: "Please enter your contact number",
                                    },
                                ],
                                options: null,
                                is_required: true,
                            },
                        ],
                    },
                    {
                        _id: "3",
                        data: {
                            name: "sam3",
                            email: "sam3@gmail.com",
                            contact: "123453",
                        },
                        form: [
                            {
                                id: new Date().valueOf(),
                                key: "first_name",
                                type: "TextField",
                                attributes: {
                                    width: "match_parent",
                                    height: "wrap_content",
                                    label: null,
                                    text: "",
                                    hint: "Name",
                                    textColor: "#FF0000",
                                    maxLengthOfChar: null,
                                    inputType: "text",
                                    display_format: null,
                                    saveRestoreLabel: null,
                                    saveRestoreDisable: null,
                                    saveRestoreVisible: null,
                                    cancelClearLabel: null,
                                    cancelClearDisable: null,
                                    cancelClearVisible: null,
                                    dropLabel: null,
                                    dropDisable: null,
                                    dropVisible: null,
                                },
                                validations: [
                                    {
                                        type: "Name",
                                        condition: null,
                                        message: "Please enter first name",
                                    },
                                ],
                                options: null,
                                is_required: true,
                            },
                            {
                                id: 2,
                                key: "email",
                                type: "TextField",
                                attributes: {
                                    width: "match_parent",
                                    height: "wrap_content",
                                    label: null,
                                    text: "",
                                    hint: "Email",
                                    textColor: "#FF0000",
                                    maxLengthOfChar: null,
                                    inputType: "email",
                                    display_format: null,
                                    saveRestoreLabel: null,
                                    saveRestoreDisable: null,
                                    saveRestoreVisible: null,
                                    cancelClearLabel: null,
                                    cancelClearDisable: null,
                                    cancelClearVisible: null,
                                    dropLabel: null,
                                    dropDisable: null,
                                    dropVisible: null,
                                },
                                validations: [
                                    {
                                        type: "Email",
                                        condition: null,
                                        message: "Please enter your email",
                                    },
                                ],
                                options: null,
                                is_required: true,
                            },

                            {
                                id: 5,
                                key: "contact",
                                type: "TextField",
                                attributes: {
                                    width: "match_parent",
                                    height: "wrap_content",
                                    label: null,
                                    text: "",
                                    hint: "Contact",
                                    textColor: "#FF0000",
                                    maxLengthOfChar: null,
                                    inputType: "number",
                                    display_format: null,
                                    saveRestoreLabel: null,
                                    saveRestoreDisable: null,
                                    saveRestoreVisible: null,
                                    cancelClearLabel: null,
                                    cancelClearDisable: null,
                                    cancelClearVisible: null,
                                    dropLabel: null,
                                    dropDisable: null,
                                    dropVisible: null,
                                },
                                validations: [
                                    {
                                        type: "Contact",
                                        condition: null,
                                        message: "Please enter your contact number",
                                    },
                                ],
                                options: null,
                                is_required: true,
                            },
                        ],
                    },
                ],
            },
            {
                element_id: "10976465",
                element_type: "form_ele",
                element_data: [
                    {
                        id: 5,
                        key: "contact",
                        type: "TextField",
                        icon: "material-solid:exposure_plus_1",
                        attributes: {
                            placeholder: "contact",
                            width: "match_parent",
                            height: "wrap_content",
                            label: null,
                            text: "",
                            hint: "Contact",
                            textColor: "#FF0000",
                            maxLengthOfChar: null,
                            inputType: "number",
                            display_format: null,
                            saveRestoreLabel: null,
                            saveRestoreDisable: null,
                            saveRestoreVisible: null,
                            cancelClearLabel: null,
                            cancelClearDisable: null,
                            cancelClearVisible: null,
                            dropLabel: null,
                            dropDisable: null,
                            dropVisible: null,
                        },
                        validations: [
                            {
                                type: "Contact",
                                condition: null,
                                message: "Please enter your contact number",
                            },
                        ],
                        options: null,
                        is_required: true,
                    },
                ],
            },
        ],
    },
];

//to get only char types from a mixed string
export function extractString(input) {
    const matches = input.match(/[a-zA-Z]+/);
    return matches ? matches[0] : "";
}
